// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "ad6aa67ef83ad82c9fa7ac5edb9ceb73"
    },
    {
        "url": "icon-96.png",
        "revision": "ff901d36635867e2bb6a93ce5918483f"
    },
    {
        "url": "icon-128.png",
        "revision": "1ab257138021798895eb1efa991a6196"
    },
    {
        "url": "icon-144.png",
        "revision": "7d7e9c841d36226b83925d954c98efdf"
    },
    {
        "url": "icon-152.png",
        "revision": "311212333d657143e198f389fbb6ee05"
    },
    {
        "url": "icon-192.png",
        "revision": "f084f9ee93fbac9028646e58b539037c"
    },
    {
        "url": "icon-384.png",
        "revision": "1e5643fa8c6c7999be6640480f4b1db5"
    },
    {
        "url": "icon-512.png",
        "revision": "2c1cbd51ef5f13bec8fa8f540b401e21"
    },
    {
        "url": "favicon.ico",
        "revision": "69b6b657ec2e67e812aeb540661e65c6"
    },
    {
        "url": "afg.png",
        "revision": "14228c51d1d2fcd8d04d2576e25966ec"
    },
    {
        "url": "ahmad.html",
        "revision": "d0ebbbe1d417d75b86ab87723510f25f"
    },
    {
        "url": "ahmad2-1.html",
        "revision": "7aa7a39af216e288f299cbbac3096ad9"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "08c0ac9ca1b42370924c8a12997f7cfd"
    },
    {
        "url": "index.html",
        "revision": "66c47f62fbb8dfbaaaf9a6a1e6cbf3e0"
    },
    {
        "url": "logo.jpg",
        "revision": "14228c51d1d2fcd8d04d2576e25966ec"
    },
    {
        "url": "logo.png",
        "revision": "14228c51d1d2fcd8d04d2576e25966ec"
    },
    {
        "url": "manifest.json",
        "revision": "4a9cd9b5e08c963bf0f65c71c0428823"
    },
    {
        "url": "offline.html",
        "revision": "93dd8135f88165fc1bbc0acf525cd1d3"
    },
    {
        "url": "sign.png",
        "revision": "9003dd31a88662933dc6a84334be992f"
    },
    {
        "url": "sw.js",
        "revision": "f97cfc3f435a9d907dab9496061969f4"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}